#! /usr/bin/env bash
# Ian Taylor 2017

# Load all necessary files containing exercises
# Use rlwrap to make the REPL actually useable ><

cd src
rlwrap scheme --load \
helpers.scm \
11_welcome_back.scm \
12_take_cover.scm \
13_hop_skip_jump.scm \
14_let_there_be_names.scm \
15_men_and_boys.scm \
